from typing import List, Optional, Tuple

VALUE_MATE: int
VALUE_DRAW: int
VALUE_NONE: int
VALUE_INFINITE: int
VALUE_KNOWN_WIN: int
VALUE_MATE_IN_MAX_PLY: int
VALUE_MATED_IN_MAX_PLY: int
VALUE_TB_WIN_IN_MAX_PLY: int
VALUE_TB_LOSS_IN_MAX_PLY: int

NOTATION_DEFAULT: int
NOTATION_SAN: int
NOTATION_LAN: int
NOTATION_SHOGI_HOSKING: int
NOTATION_SHOGI_HODGES: int
NOTATION_SHOGI_HODGES_NUMBER: int
NOTATION_JANGGI: int
NOTATION_XIANGQI_WXF: int
NOTATION_THAI_SAN: int
NOTATION_THAI_LAN: int

FEN_INVALID_MOVE: int
FEN_OK: int
FEN_INVALID_PROMOTED_PIECE: int

def version() -> Tuple[int, int, int]: ...
def info() -> str: ...
def variants() -> List[str]: ...
def set_option(name: str, value: object) -> None: ...
def load_variant_config(config: str) -> None: ...
def start_fen(variant: str) -> str: ...
def two_boards(variant: str) -> bool: ...
def captures_to_hand(variant: str) -> bool: ...
def from_san(variant: str, fen: str, san: str, chess960: bool = False, notation: int = NOTATION_DEFAULT) -> Optional[str]: ...
def get_san(variant: str, fen: str, move: str, chess960: bool = False, notation: int = NOTATION_DEFAULT) -> str: ...
def get_san_moves(variant: str, fen: str, moves: List[str], chess960: bool = False, notation: int = NOTATION_DEFAULT) -> List[str]: ...
def legal_moves(variant: str, fen: str, moves: List[str], chess960: bool = False, notation: int = NOTATION_DEFAULT) -> List[str]: ...
def get_fen(variant: str, fen: str, moves: List[str], chess960: bool = False, sfen: bool = False, show_promoted: bool = False, count_started: int = 0) -> str: ...
def evaluate(variant: str, fen: str, moves: List[str], chess960: bool = False) -> int: ...
def gives_check(variant: str, fen: str, moves: List[str], chess960: bool = False) -> bool: ...
def is_capture(variant: str, fen: str, moves: List[str], move: str, chess960: bool = False) -> bool: ...
def piece_to_partner(variant: str, fen: str, moves: List[str], chess960: bool = False) -> str: ...
def game_result(variant: str, fen: str, moves: List[str], chess960: bool = False) -> int: ...
def is_immediate_game_end(variant: str, fen: str, moves: List[str], chess960: bool = False) -> Tuple[bool, int]: ...
def is_optional_game_end(variant: str, fen: str, moves: List[str], chess960: bool = False, count_started: int = 0) -> Tuple[bool, int]: ...
def has_insufficient_material(variant: str, fen: str, moves: List[str], chess960: bool = False) -> Tuple[bool, bool]: ...
def validate_fen(fen: str, variant: str, chess960: bool = False) -> int: ...
def validate_position(variant: str, fen: str, moves: List[str], chess960: bool = False) -> int: ...
def get_fog_fen(fen: str, variant: str, chess960: bool = False) -> str: ...
