import pyffish as sf

cfg = """
[testpush:chess]
customPiece1 = p:P
pushingStrength = p:1
"""
sf.load_variant_config(cfg)
variant = "testpush"
fen = "8/8/8/8/3p4/3P4/8/8 w - - 0 1"
# Note: legal_moves for pushing variants can be tricky if they are not generated by default.
# But with pushingStrength > 0, they should be in the move list.
moves = sf.legal_moves(variant, fen, [])
print("Legal moves:", moves)
if "d3d4" in moves:
    print("Found push move d3d4")
else:
    # If d3d4 is not in legal moves, maybe it needs a different notation or 
    # the move generator needs more config. 
    # In some FS versions, push moves are only generated if certain flags are set.
    pass
